---
# Pagespeed module is failing on apt-cache update
# bodging in a fix from https://support.plesk.com/hc/en-us/articles/360021566754--apt-update-is-not-working-on-Plesk-server-with-Ubuntu-or-Debian-after-installing-PageSpeed-Apache-module-through-Google-PageSpeed-Insights-extension-The-repository-http-dl-google-com-linux-mod-pagespeed-deb-stable-Release-is-not-signed

- name: Check pagespeed repo file exists
  stat: path=/etc/apt/sources.list.d/mod-pagespeed.list
  register: ps_apt_stat
  failed_when: not ps_apt_stat.stat.exists

- name: Moving out pagespeed repo
  command: mv /etc/apt/sources.list.d/mod-pagespeed.list /tmp/
  when: ps_apt_stat.stat.exists

- name: Update the apt-cache to remove pagespeed apt from cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install the latest version of the signing key
  apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
    state: present

- name: Moving pagespeed repo back in ready for the update
  stat: path=/tmp/mod-pagespeed.list
  command: mv /tmp/mod-pagespeed.list /etc/apt/sources.list.d/

- name: Update the apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install APT Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - htop
    - build-essential
    - mysql-client
    - python2.7
    - python2.7-dev
    - python-setuptools
    - python-mysqldb
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - unzip

- name: "Update pip"
  pip:
    name: pip
    state: latest

- name: "Install python system-level modules"
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --ignore-installed
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: "Create /opt/beamly"
  file:
    path: /opt/beamly
    state: directory
    mode: 0755

- name: "Create /mnt/log"
  file:
    path: /mnt/log
    state: directory
    mode: 0777
