---
- name: Update the apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install APT Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - htop
    - build-essential
    - mysql-client
    - python2.7
    - python2.7-dev
    - python-setuptools
    - python-mysqldb
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - unzip

- name: "Update pip"
  pip:
    name: pip
    state: latest

- name: "Install python system-level modules"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: "Create /opt/beamly"
  file:
    path: /opt/beamly
    state: directory
    mode: 0755

- name: "Create /mnt/log"
  file:
    path: /mnt/log
    state: directory
    mode: 0777
