---
- name: Update the apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install APT Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - htop
    - build-essential
    - mysql-client
    - php5.6-dom
    - php5.6-mbstring
    - php-memcache
    - python2.7
    - python2.7-dev
    - python-setuptools
    - python-mysqldb
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - unzip
