---
- name: Add deadsnakes-2.7 ppa
  apt_repository: repo="ppa:fkrull/deadsnakes-python2.7"
  when: upgrade_python

- name: Update the apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install APT Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - htop
    - build-essential
    - mysql-client
    - python2.7
    - python2.7-dev
    - python-setuptools
    - python-mysqldb
    - python-virtualenv
    - libffi-dev
    - libssl-dev
